---
title: "Lịch sử ra đời các phương pháp dự báo chuỗi thời gian"
author: "Nguyễn Ngọc Bình"
date: "`r format(Sys.Date(), '%Y-%m-%d')`"
output: 
  html_document:
    code_download: false
    code_folding: show
    number_sections: yes
    theme: "default"
    toc: TRUE
    toc_float: TRUE
    dev: 'svg'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Giới thiệu

- Dự báo chuỗi thời gian là một lĩnh vực nhỏ của phân tích chuỗi thời gian, trong đó các phép đo lịch sử được lập mô hình để mô tả các đặc điểm cơ bản của những thứ có thể quan sát được và được ngoại suy trong tương lai.

- Trong một vài thập kỷ, lĩnh vực phân tích chuỗi thời gian đã bị thống trị bởi phương pháp thống kê. Một trong những mô hình quan trọng nhất và thường được sử dụng là Đường trung bình động tích hợp tự hồi quy (AutoRegressive Integrated Moving Average - ARIMA), có thể được xây dựng nhanh chóng nhờ phương pháp Box – Jenkins. Họ mô hình ARIMA có tính linh hoạt tuyệt vời để trình bày các chuỗi thời gian khác nhau. Tuy nhiên, nó có giới hạn do giả định về độ tuyến tính của chuỗi thời gian.

- Một phương pháp thống kê thống trị khác và được sử dụng rộng rãi là ExponenTial Smoothing (ETS), được đề xuất vào những năm 1950. Nó thường được coi là một giải pháp thay thế cho các mô hình ARIMA. Trong khi họ ARIMA phát triển một mô hình trong đó dự đoán là tổng tuyến tính có trọng số của các quan sát trong quá khứ gần đây hoặc độ trễ, thì các dự báo do ETS tạo ra là trung bình có trọng số của các quan sát trong quá khứ, với trọng số giảm dần theo cấp số nhân với các quan sát xa hơn.

- Cuộc thi **M** do giáo sư Spyros Makridakis khởi xướng. Có các cuộc thi mở khác nhau (M1 – M5) dành riêng cho việc so sánh hiệu suất của các phương pháp dự báo khác nhau. Đặc biệt, phương pháp Theta đã thành công ấn tượng trong Cuộc thi M3 và do đó được sử dụng trong Cuộc thi M4 như một tiêu chuẩn. Nó được đề xuất lần đầu tiên bởi Assimakopoulos et al. và sau đó được mở rộng sang dự báo chuỗi thời gian kinh tế vĩ mô và tài chính đa biến. Hyndman đã chứng minh phương pháp Theta được áp dụng trong Cuộc thi M3 tương đương với phương pháp làm mịn hàm mũ đơn giản với độ lệch.

- Chuỗi thời gian cũng có thể có nhiều mẫu cơ bản và việc phân tích có thể tiết lộ chúng bằng cách chia chuỗi thời gian thành nhiều thành phần. Trong phần này, tôi tập trung vào phân rã STL. 
STL là viết tắt của phân tích theo mùa-xu hướng bằng cách sử dụng LOESS ( Seasonal-Trend decomposition), trong đó LOESS là  **LOcal regrESSion**, được đề xuất bởi Robert et al.(1990) đóng góp vào một phương pháp phân rã mạnh đối với các bất thường.

- Trí tuệ nhân tạo (AI) đã đạt được sự nổi bật đáng kể trong thập kỷ qua, đặc biệt là trong nhận dạng đối tượng, xử lý ngôn ngữ tự nhiên (NLP) và lái xe tự động. Mạng Nơ-ron phức hợp (CNN) đã cách mạng hóa lĩnh vực thị giác máy tính. Mạng Nơ-ron định kỳ (RNN) được hưởng lợi từ rất nhiều thành quả NLP, chẳng hạn như dịch máy và nhận dạng giọng nói. Trong lĩnh vực chuỗi thời gian, nhiều phương pháp học máy như hồi quy vectơ hỗ trợ (SVR), mạng nơ-ron, cây phân loại và hồi quy (CART), và hồi quy k -lân cận (kNN) đã được chứng minh là có thể lập mô hình và dự báo chuỗi thời gian.

- Có một số cuộc thảo luận về việc so sánh hiệu suất của các phương pháp dự báo khác nhau. Ahmed và cộng sự đã thực hiện một so sánh thực nghiệm của tám mô hình học máy trong chuỗi 1045 tháng liên quan đến Cuộc thi M3, nhưng chỉ thực hiện dự báo trước một bước. Makrirdakis và cộng sự đã thực hiện một số công trình tương tự, so sánh các phương pháp thống kê và học máy, nhưng không có bất kỳ phương pháp _phân rã_ nào được đưa vào như một bước tiền xử lý. Sử dụng tập dữ liệu cuộc thi M1, Theodosieu đã so sánh phương pháp dựa trên STL mới với một số điểm chuẩn phổ biến nhưng không kết hợp STL với chúng và chỉ xem xét dự báo tối đa 18 tháng.

- Vì bước tiền xử lý thường đóng một phần không thể thiếu trong các mô hình dự báo và tác động đáng kể đến kết quả, chúng tôi đề xuất tiến hành một công việc so sánh mới để xác định lợi ích của nó: (1) bằng cách khám phá sự phân rã STL khi sử dụng nó như một bước tiền xử lý cho tất cả các phương pháp; và (2) bằng cách xem xét thời gian dự báo dài.

- Phần còn lại của bài này được tổ chức như sau. Trong phần tiếp theo, tôi trình bày một mô tả ngắn gọn về tất cả các mô hình liên quan và các phương pháp phân rã. Phần 3 trình bày cách tôi tổ chức và tiến hành các thực nghiệm. Trong Phần 4, tôi trình bày các kết quả so sánh và các cuộc thảo luận dựa trên các kết quả này. Phần 5 đưa ra kết luận.

# Autoregressive integrated moving average (ARIMA)

## Lịch sử ra đời

- Tác giả

- 

## Các biến thể (family models)

# ExponenTial Smoothing (ETS)

